name: Build
on:
  push:
    branches: [main, features/*]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install LLVM (Unix)
        if: matrix.os != 'windows-latest'
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"
          env: true

      - name: Setup MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-llvm-21 mingw-w64-ucrt-x86_64-clang-21
            mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja

      - name: Build (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DLLVM_DIR="${{ env.LLVM_PATH }}/lib/cmake/llvm"
          cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          export CC=clang-21
          export CXX=clang++-21
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: veoc-${{ matrix.os }}
          path: |
            build/veoc
            build/veoc.exe
            build/${{ matrix.build_type }}/veoc.exe
          if-no-files-found: error
